const app=document.getElementById('app');
const ROOT_ADMIN='admin';
let users=JSON.parse(localStorage.getItem('chathub_users_v3')||'[]');
let chats=JSON.parse(localStorage.getItem('chathub_chats_v3')||'[]');
let adminMessages=JSON.parse(localStorage.getItem('chathub_admin_messages_v3')||'[]');
let current=null;
if(!users.length){users=[{id:1,name:'Alex',email:'alex@example.com',banned:false,admin:false},{id:2,name:'Sam',email:'sam@example.com',banned:false,admin:false},{id:3,name:'Jamie',email:'jamie@example.com',banned:true,admin:false},{id:4,name:'Jordan',email:'jordan@example.com',banned:false,admin:true}];saveUsers()}
function saveUsers(){localStorage.setItem('chathub_users_v3',JSON.stringify(users))}
function save(){localStorage.setItem('chathub_chats_v3',JSON.stringify(chats))}
function saveAdmin(){localStorage.setItem('chathub_admin_messages_v3',JSON.stringify(adminMessages))}
function login(){app.innerHTML=`<main class="login"><section class="card"><h1>ChatHub</h1><p>Sign in to continue.</p><div class="field"><label>Username</label><input id="u"></div><div class="field"><label>Password</label><input id="p" type="password"></div><div id="err" class="error"></div><button class="primary" onclick="doLogin()">Sign in</button><p class="hint">Demo root admin: admin / admin123</p></section></main>`}
function doLogin(){if(u.value===ROOT_ADMIN&&p.value==='admin123')start(true);else{let found=users.find(x=>x.email===u.value&&x.admin);if(found&&p.value==='admin123'&&!found.banned)start(true);else err.textContent='Incorrect login or you are not an active admin.'}}
function start(isAdmin){if(!chats.length){chats=[{id:Date.now(),title:'New chat',messages:[]}];save()}current=chats[0].id;render(isAdmin)}
function render(isAdmin){app.innerHTML=`<div class="app"><header class="top"><div class="logo">ChatHub</div><div class="spacer"></div>${isAdmin?'<button class="adminbtn" onclick="adminPanel()">⚙ Admin Panel</button>':''}<button class="logout" onclick="login()">Log out</button></header><div class="body"><aside class="side"><button class="new" onclick="newChat()">＋ New chat</button><div class="history" id="history"></div></aside><main class="main"><div class="msgs" id="msgs"></div><div class="composer"><div class="compose"><textarea id="input" placeholder="Message ChatHub..." onkeydown="key(event)"></textarea><button class="send" onclick="send()">↑</button></div></div></main></div></div>`;update()}
function update(){history.innerHTML=chats.map(c=>`<div class="item" onclick="select(${c.id})">${esc(c.title)}</div>`).join('');let c=chats.find(x=>x.id===current)||chats[0];current=c.id;msgs.innerHTML=c.messages.length?c.messages.map(m=>`<div class="msg ${m.role}"><div class="av">${m.role==='user'?'You':'AI'}</div><div class="bubble">${esc(m.text)}</div></div>`).join(''):`<div class="welcome"><h1>How can I help?</h1><p>Ask ChatHub anything.</p></div>`}
function newChat(){chats.unshift({id:Date.now(),title:'New chat',messages:[]});current=chats[0].id;save();update()}
function select(id){current=id;update()}
function key(e){if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}
function send(){let text=input.value.trim();if(!text)return;let c=chats.find(x=>x.id===current);c.messages.push({role:'user',text});if(c.title==='New chat')c.title=text.slice(0,35);input.value='';save();update();setTimeout(()=>{c.messages.push({role:'assistant',text:'This is a demo ChatHub response. A real AI backend can be connected here.'});save();update()},400)}
function adminPanel(){app.innerHTML=`<div class="app"><header class="top"><div class="logo">ChatHub</div><div class="spacer"></div><strong>ADMIN</strong><button class="back" onclick="start(true)">Back to chat</button><button class="logout" onclick="login()">Log out</button></header><section class="admin"><h1>Admin Panel</h1><p class="small">Manage users, administrators and admin chat.</p><div class="stat">Users<h2>${users.length}</h2></div><div class="stat">Admins<h2>${users.filter(u=>u.admin).length+1}</h2></div><div class="stat">Banned<h2>${users.filter(u=>u.banned).length}</h2></div><div class="tabs"><button class="tab active" onclick="adminPanel()">Users</button><button class="tab" onclick="adminChat()">Admin Chat</button></div><div class="admin-grid"><section class="panel"><h2>Users & admins</h2><div class="userrow"><div><strong>Root Admin</strong><br><span class="small">admin · Owner</span></div><span class="role admin">ROOT ADMIN</span></div>${users.map((u,i)=>`<div class="userrow"><div><strong>${esc(u.name)}</strong><br><span class="small">${esc(u.email)} · ${u.banned?'BANNED':u.admin?'ADMIN':'User'}</span></div><div class="actions">${u.admin?`<button class="demote" onclick="toggleAdmin(${i})">Remove admin</button>`:`<button class="promote" onclick="toggleAdmin(${i})">Promote admin</button>`}${u.banned?`<button class="unban" onclick="toggleBan(${i})">Unban</button>`:`<button class="ban" onclick="toggleBan(${i})">Ban</button>`}</div></div>`).join('')}</section><section class="panel"><h2>Admin permissions</h2><p>Admins can access the Admin Panel, use Admin Chat, promote or demote other users, and ban or unban users.</p><p class="small">The root admin cannot be removed through this demo.</p></section></div></section></div>`}
function toggleAdmin(i){if(users[i].banned){alert('Unban this user before promoting them.');return}users[i].admin=!users[i].admin;saveUsers();adminPanel()}
function toggleBan(i){users[i].banned=!users[i].banned;saveUsers();adminPanel()}
function adminChat(){app.innerHTML=`<div class="app"><header class="top"><div class="logo">ChatHub</div><div class="spacer"></div><strong>ADMIN</strong><button class="back" onclick="adminPanel()">Users</button><button class="back" onclick="start(true)">Chat</button><button class="logout" onclick="login()">Log out</button></header><section class="admin"><h1>Admin Chat</h1><p class="small">Private chat area for admins.</p><div class="panel adminchat"><div class="adminmsgs" id="adminmsgs">${adminMessages.length?adminMessages.map(m=>`<div class="msg"><div class="av">A</div><div class="bubble"><b>${esc(m.name)}</b><br>${esc(m.text)}</div></div>`).join(''):'<p class="small">No admin messages yet.</p>'}</div><div class="admincompose"><input id="admininput" placeholder="Message the admin team..." onkeydown="adminKey(event)"><button class="adminsend" onclick="sendAdmin()">Send</button></div></div></section></div>`}
function adminKey(e){if(e.key==='Enter')sendAdmin()}
function sendAdmin(){let x=admininput.value.trim();if(!x)return;adminMessages.push({name:'Admin',text:x});admininput.value='';saveAdmin();adminChat()}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
login();
